spring:
    profiles:
        active:
            - dev
            
---
server:
    port: 8003
spring:
    profiles: dev
    application:
        name: microservicecloud-dept

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: micro-dept8003
    prefer-ip-address: true
    
    
---
server:
    port: 8003
spring:
    profiles: test
    application:
        name: microservicecloud-confit-dept-client

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
